import { spawn } from 'child_process';
import path from 'path';
import {
  app,
  type BaseWindow,
  BrowserWindow,
  Menu,
  type MenuItemConstructorOptions,
  nativeTheme,
  net,
  protocol,
  shell,
  session,
} from 'electron';
import { closeDatabase, initDatabase } from './main/db';
import { resolveImagePath } from './main/image-protocol';
import { registerClipboardIpcHandler, registerIpcHandlers } from './main/ipc';
import { installEditorContextMenu } from './main/editor-context-menu';
import { applySpellCheckPreferences } from './main/spellcheck';
import { initUpdater } from './main/updater';
import { isAllowedExternal } from './main/url-policy';
import {
  applyChromeToAllWindows,
  bootstrapChromeFor,
  resolveTheme,
  TITLEBAR_OVERLAY_HEIGHT,
} from './main/window-chrome';
import { getKeybindings } from './main/repos/keybindings';
import { toElectronAccelerator } from './shared/keybindings';

// CSP applies to packaged builds. Dev runs through webpack-dev-server which sets
// its own (looser) CSP via WebpackPlugin.devContentSecurityPolicy — HMR needs
// 'unsafe-eval', which we deliberately drop here.
//
// All renderer scripts are loaded from 'self' (the renderer bundle and
// theme-bootstrap.js, both emitted to the renderer output dir).
const RENDERER_CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: lychee-image: https:",
  "media-src 'self' lychee-image: https:",
  "connect-src 'self' https:",
  "frame-src 'none'",
  "object-src 'none'",
  "base-uri 'self'",
].join('; ');

function registerContentSecurityPolicy(): void {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    if (details.resourceType !== 'mainFrame') {
      callback({});
      return;
    }
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [RENDERER_CSP],
      },
    });
  });
}

// Register custom protocol for serving local image files
protocol.registerSchemesAsPrivileged([
  { scheme: 'lychee-image', privileges: { bypassCSP: true, stream: true, supportFetchAPI: true } },
]);

// Used for Linux/Windows window chrome; macOS reads the icon from the bundle's .icns.
// In production only the webpack output lives inside app.asar, so build/ isn't
// reachable from __dirname — forge's extraResource copies icon.png into
// process.resourcesPath instead.
const windowIconPath = app.isPackaged
  ? path.join(process.resourcesPath, 'icon.png')
  : path.resolve(__dirname, '..', '..', 'build', 'icon.png');

const LYCHEE_WEBSITE_URL = 'https://lycheenote.com';
const LYCHEE_REPO_URL = 'https://github.com/reddpy/lychee';
const LYCHEE_ISSUES_URL = 'https://github.com/reddpy/lychee/issues';

// `clickedWindow` is the window passed into the menu item's click callback (typed
// as BaseWindow by Electron's API). Narrows to BrowserWindow and falls back to
// focused/first window so programmatic .click() (e.g. E2E tests, or any case
// where OS focus isn't on a Lychee window) still routes the event.
function sendMenuEvent(clickedWindow: BaseWindow | undefined, channel: string): void {
  const fromClick = clickedWindow instanceof BrowserWindow ? clickedWindow : null;
  const win = fromClick ?? BrowserWindow.getFocusedWindow() ?? BrowserWindow.getAllWindows()[0];
  win?.webContents.send(channel);
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
//
// Issue #200: electron-squirrel-startup shells out to `Update.exe --createShortcut`
// on BOTH --squirrel-install AND --squirrel-updated, with no `-l` flag, which
// makes Squirrel default to creating *both* Desktop and Start Menu shortcuts on
// every update — recreating a desktop shortcut the user previously deleted.
//
// We intercept only those two events to:
//   --squirrel-install: create a Start-Menu shortcut only (no Desktop).
//   --squirrel-updated: do nothing (preserve whatever shortcuts the user has).
// All other squirrel events (--squirrel-uninstall, --squirrel-obsolete, future
// additions) fall through to electron-squirrel-startup unchanged, so we keep its
// well-tested handling for the lifecycle stages that don't trigger the bug.
function interceptSquirrelShortcutEvents(): boolean {
  if (process.platform !== 'win32' || process.argv.length < 2) return false;
  const cmd = process.argv[1];
  if (cmd !== '--squirrel-install' && cmd !== '--squirrel-updated') return false;

  if (cmd === '--squirrel-install') {
    const updateExe = path.resolve(path.dirname(process.execPath), '..', 'Update.exe');
    const exeName = path.basename(process.execPath);
    spawn(updateExe, [`--createShortcut=${exeName}`, '-l', 'StartMenu'], { detached: true });
  }
  // --squirrel-updated: intentionally no-op; do NOT recreate shortcuts.
  app.quit();
  return true;
}

if (interceptSquirrelShortcutEvents()) {
  // app.quit() above; fall through to event loop.
} else if (require('electron-squirrel-startup')) {
  app.quit();
}

// Edit > Find is deliberately omitted: its Cmd+F accelerator re-injects a
// synthetic keydown into the renderer under Playwright/CDP input, double-firing
// our in-note find toggle. The rest of the standard role-based accelerators
// (Cmd+W/M/R/Opt+I/Q/Z/C/V/X/A) keep working.
function buildAppMenu(): Menu {
  const isMac = process.platform === 'darwin';
  const keybindings = getKeybindings();

  const newNoteItem: MenuItemConstructorOptions = {
    label: 'New Note',
    accelerator: toElectronAccelerator(keybindings['app.newNote']),
    click: (_item, win) => sendMenuEvent(win, 'menu:new-note'),
  };

  const settingsItem: MenuItemConstructorOptions = {
    label: 'Settings…',
    accelerator: toElectronAccelerator(keybindings['app.openSettings']),
    click: (_item, win) => sendMenuEvent(win, 'menu:open-settings'),
  };

  const closeTabItem: MenuItemConstructorOptions = {
    label: 'Close Tab',
    accelerator: toElectronAccelerator(keybindings['tabs.close']),
    click: (_item, win) => sendMenuEvent(win, 'menu:close-tab'),
  };

  const reopenClosedTabItem: MenuItemConstructorOptions = {
    label: 'Reopen Closed Tab',
    accelerator: toElectronAccelerator(keybindings['tabs.reopenClosed']),
    click: (_item, win) => sendMenuEvent(win, 'menu:reopen-closed-tab'),
  };

  const template: MenuItemConstructorOptions[] = [
    ...(isMac
      ? ([
          {
            label: app.name,
            submenu: [
              { role: 'about' },
              { type: 'separator' },
              settingsItem,
              { type: 'separator' },
              { role: 'services' },
              { type: 'separator' },
              { role: 'hide' },
              { role: 'hideOthers' },
              { role: 'unhide' },
              { type: 'separator' },
              { role: 'quit' },
            ],
          } as MenuItemConstructorOptions,
        ])
      : []),
    {
      label: 'File',
      submenu: [
        newNoteItem,
        { type: 'separator' },
        closeTabItem,
        reopenClosedTabItem,
        ...((isMac
          ? []
          : [{ type: 'separator' }, settingsItem, { type: 'separator' }, { role: 'quit' }]) as MenuItemConstructorOptions[]),
      ],
    },
    {
      label: 'Edit',
      submenu: [
        {
          label: 'Undo',
          accelerator: toElectronAccelerator(keybindings['editor.undo']),
          click: (_item, win) => sendMenuEvent(win, 'menu:undo'),
        },
        {
          label: 'Redo',
          accelerator: toElectronAccelerator(keybindings['editor.redo']),
          click: (_item, win) => sendMenuEvent(win, 'menu:redo'),
        },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        ...((isMac
          ? [
              { role: 'pasteAndMatchStyle' },
              { role: 'delete' },
              { role: 'selectAll' },
            ]
          : [
              { role: 'delete' },
              { type: 'separator' },
              { role: 'selectAll' },
            ]) as MenuItemConstructorOptions[]),
      ],
    },
    {
      label: 'View',
      submenu: [
        { role: 'reload' },
        { role: 'forceReload' },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { role: 'minimize' },
        { role: 'zoom' },
        ...((isMac
          ? [{ type: 'separator' }, { role: 'front' }]
          : [{ role: 'close' }]) as MenuItemConstructorOptions[]),
      ],
    },
    {
      role: 'help',
      submenu: [
        {
          label: 'Lychee Website',
          click: () => void shell.openExternal(LYCHEE_WEBSITE_URL),
        },
        {
          label: 'View on GitHub',
          click: () => void shell.openExternal(LYCHEE_REPO_URL),
        },
        {
          label: 'Report an Issue',
          click: () => void shell.openExternal(LYCHEE_ISSUES_URL),
        },
        ...((isMac
          ? []
          : [{ type: 'separator' }, { role: 'about' }]) as MenuItemConstructorOptions[]),
      ],
    },
  ];
  return Menu.buildFromTemplate(template);
}

const createWindow = (): BrowserWindow => {
  const isMac = process.platform === 'darwin';
  const theme = resolveTheme();
  const chrome = bootstrapChromeFor(theme);

  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    minHeight: 480,
    minWidth: 680,
    icon: windowIconPath,
    show: false,
    backgroundColor: chrome.bg,
    titleBarStyle: isMac ? 'hiddenInset' : 'hidden',
    trafficLightPosition: isMac ? { x: 12, y: 14 } : undefined,
    // Win/Linux: paint native min/max/close as an overlay on the right while we
    // own the rest of the title bar. Renderer hosts a hamburger menu in its place.
    titleBarOverlay: isMac
      ? undefined
      : { color: chrome.color, symbolColor: chrome.symbolColor, height: TITLEBAR_OVERLAY_HEIGHT },
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  installEditorContextMenu(mainWindow);

  if (!isMac) {
    // Keep Menu.setApplicationMenu registered so accelerators (Ctrl+N etc.) still
    // fire; just hide the menu strip — hamburger replaces it. Alt-toggle is left
    // disabled to avoid the strip flashing in over our custom title bar.
    mainWindow.setMenuBarVisibility(false);
    mainWindow.setAutoHideMenuBar(true);
  }

  // Show window once the renderer has painted — prevents white flash
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  return mainWindow;
};

// Block new BrowserWindow creation and unexpected top-level navigation. Allowed
// external URLs are handed off to the OS so they open in the user's default
// browser; everything else is denied. Registered before createWindow so the
// listener fires for the main window's webContents on creation.
function installNavigationGuards(): void {
  app.on('web-contents-created', (_event, contents) => {
    contents.setWindowOpenHandler(({ url }) => {
      if (isAllowedExternal(url)) {
        void shell.openExternal(url);
      }
      return { action: 'deny' };
    });

    contents.on('will-navigate', (event, url) => {
      if (url !== contents.getURL()) {
        event.preventDefault();
      }
    });
  });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  app.setAboutPanelOptions({
    applicationName: 'Lychee',
    applicationVersion: app.getVersion(),
    copyright: `© ${new Date().getFullYear()} Lychee`,
    website: LYCHEE_WEBSITE_URL,
    iconPath: windowIconPath,
  });

  // Repaint title bar overlay (Win/Linux) when OS theme flips while mode='system'.
  nativeTheme.on('updated', () => {
    applyChromeToAllWindows();
  });

  installNavigationGuards();
  if (app.isPackaged) {
    registerContentSecurityPolicy();
  }

  // Handle lychee-image:// protocol — serves files from userData/images/
  protocol.handle('lychee-image', (request) => {
    const imagesDir = path.join(app.getPath('userData'), 'images');
    const resolved = resolveImagePath(request.url, imagesDir);
    if (!resolved.ok) {
      return new Response(null, { status: 403 });
    }
    return net.fetch(`file://${resolved.path}`);
  });

  const { dbPath } = initDatabase();
  console.log(`[db] sqlite: ${dbPath}`);

  applySpellCheckPreferences();
  Menu.setApplicationMenu(buildAppMenu());

  // Must register IPC handlers before createWindow loads the renderer URL —
  // the renderer can fire IPC during early hydration (e.g. theme/settings)
  // and would otherwise hit "No handler registered" if the window is created first.
  registerIpcHandlers({
    onKeybindingsChanged: () => Menu.setApplicationMenu(buildAppMenu()),
  });
  registerClipboardIpcHandler();
  createWindow();

  // Start the auto-updater after the window exists so early status broadcasts
  // reach a live renderer (late joiners pull current state via update.getStatus).
  initUpdater();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  closeDatabase();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
