import path from 'path';
import {
  app,
  BrowserWindow,
  Menu,
  type MenuItemConstructorOptions,
  nativeTheme,
  net,
  protocol,
  shell,
} from 'electron';
import { closeDatabase, initDatabase } from './main/db';
import { registerIpcHandlers } from './main/ipc';
import { getSetting } from './main/repos/settings';
import { isAllowedExternal } from './main/url-policy';

// Register custom protocol for serving local image files
protocol.registerSchemesAsPrivileged([
  { scheme: 'lychee-image', privileges: { bypassCSP: true, stream: true, supportFetchAPI: true } },
]);

// Used for Linux/Windows window chrome; macOS reads the icon from the bundle's .icns.
const windowIconPath = path.resolve(__dirname, '..', '..', 'build', 'icon.png');
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Mirrors Electron's stock macOS menu but omits Edit > Find. Find's Cmd+F
// accelerator re-injects a synthetic keydown into the renderer under
// Playwright/CDP input, double-firing our in-note find toggle. Removing only
// that submenu keeps Cmd+W/M/R/Opt+I/Q/Z/C/V/X/A working as before.
function buildAppMenu(): Menu {
  const isMac = process.platform === 'darwin';
  const template: MenuItemConstructorOptions[] = [
    ...(isMac
      ? ([
          {
            label: app.name,
            submenu: [
              { role: 'about' },
              { type: 'separator' },
              { role: 'services' },
              { type: 'separator' },
              { role: 'hide' },
              { role: 'hideOthers' },
              { role: 'unhide' },
              { type: 'separator' },
              { role: 'quit' },
            ],
          } as MenuItemConstructorOptions,
        ])
      : []),
    {
      label: 'File',
      submenu: [isMac ? { role: 'close' } : { role: 'quit' }],
    },
    {
      label: 'Edit',
      submenu: [
        { role: 'undo' },
        { role: 'redo' },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        ...((isMac
          ? [
              { role: 'pasteAndMatchStyle' },
              { role: 'delete' },
              { role: 'selectAll' },
            ]
          : [
              { role: 'delete' },
              { type: 'separator' },
              { role: 'selectAll' },
            ]) as MenuItemConstructorOptions[]),
      ],
    },
    {
      label: 'View',
      submenu: [
        { role: 'reload' },
        { role: 'forceReload' },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { role: 'minimize' },
        { role: 'zoom' },
        ...((isMac
          ? [{ type: 'separator' }, { role: 'front' }]
          : [{ role: 'close' }]) as MenuItemConstructorOptions[]),
      ],
    },
  ];
  return Menu.buildFromTemplate(template);
}

function resolveBackgroundColor(): string {
  try {
    const mode = getSetting('theme');
    const dark =
      mode === 'dark' ||
      (mode === 'system' && nativeTheme.shouldUseDarkColors);
    return dark ? '#1d1816' : '#fefefd';
  } catch {
    // DB not initialized or table missing (e.g. hot-reload before migration)
    return '#fefefd';
  }
}

const createWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    minHeight: 480,
    minWidth: 680,
    icon: windowIconPath,
    show: false,
    backgroundColor: resolveBackgroundColor(),
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    trafficLightPosition:
      process.platform === 'darwin' ? { x: 12, y: 14 } : undefined,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // Show window once the renderer has painted — prevents white flash
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  return mainWindow;
};

// Block new BrowserWindow creation and unexpected top-level navigation. Allowed
// external URLs are handed off to the OS so they open in the user's default
// browser; everything else is denied. Registered before createWindow so the
// listener fires for the main window's webContents on creation.
function installNavigationGuards(): void {
  app.on('web-contents-created', (_event, contents) => {
    contents.setWindowOpenHandler(({ url }) => {
      if (isAllowedExternal(url)) {
        void shell.openExternal(url);
      }
      return { action: 'deny' };
    });

    contents.on('will-navigate', (event, url) => {
      if (url !== contents.getURL()) {
        event.preventDefault();
      }
    });
  });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  Menu.setApplicationMenu(buildAppMenu());

  installNavigationGuards();

  // Handle lychee-image:// protocol — serves files from userData/images/
  protocol.handle('lychee-image', (request) => {
    // URL format: lychee-image://image/<filename>
    const filePath = decodeURIComponent(request.url.replace('lychee-image://image/', ''));
    const fullPath = path.join(app.getPath('userData'), 'images', filePath);
    return net.fetch(`file://${fullPath}`);
  });

  const { dbPath } = initDatabase();
  console.log(`[db] sqlite: ${dbPath}`);

  // Must register IPC handlers before createWindow loads the renderer URL —
  // the renderer can fire IPC during early hydration (e.g. theme/settings)
  // and would otherwise hit "No handler registered" if the window is created first.
  registerIpcHandlers();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  closeDatabase();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
